void testMemcpyED();
void testMemcmpED();
void testMemchrED();
void testMemmoveED();
void testMemsetED();
void testStrcatED();
void testStrchrED();
void compareED(const void* val1, const void* val2, size_t size);
void testStrTokED();
void testStrLenED();